// wordPack.js — v10-fixed-b2
// Categories are now SHORT 1-2 word labels, not descriptive sentences.
export const WORD_PACKS = [
  {
    name: 'Places',
    words: [
      { word:{ en:'Airport',      ar:'مطار'           }, category:{ en:'Travel',     ar:'سفر'      } },
      { word:{ en:'Hospital',     ar:'مستشفى'         }, category:{ en:'Health',      ar:'صحة'       } },
      { word:{ en:'Bank',         ar:'بنك'              }, category:{ en:'Finance',     ar:'مال'       } },
      { word:{ en:'Casino',       ar:'كازينو'          }, category:{ en:'Games',       ar:'ترفيه'      } },
      { word:{ en:'University',   ar:'جامعة'           }, category:{ en:'Education',   ar:'تعليم'      } },
      { word:{ en:'Stadium',      ar:'ملعب'            }, category:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Mosque',       ar:'مسجد'            }, category:{ en:'Religion',    ar:'دين'        } },
      { word:{ en:'Prison',       ar:'سجن'              }, category:{ en:'Justice',     ar:'قانون'      } },
      { word:{ en:'Museum',       ar:'متحف'            }, category:{ en:'Culture',     ar:'ثقافة'      } },
      { word:{ en:'Market',       ar:'سوق'              }, category:{ en:'Commerce',    ar:'تجارة'      } },
      { word:{ en:'Farm',         ar:'مزرعة'           }, category:{ en:'Nature',      ar:'طبيعة'      } },
      { word:{ en:'Space Station',ar:'محطة فضائية'    }, category:{ en:'Science',     ar:'علوم'       } },
      { word:{ en:'Restaurant',   ar:'مطعم'           }, category:{ en:'Food',        ar:'طعام'       } },
      { word:{ en:'Library',      ar:'مكتبة'           }, category:{ en:'Education',   ar:'تعليم'      } },
      { word:{ en:'Embassy',      ar:'سفارة'           }, category:{ en:'Politics',    ar:'سياسة'      } },
      { word:{ en:'Theater',      ar:'مسرح'            }, category:{ en:'Arts',        ar:'فنون'       } },
      { word:{ en:'Laboratory',   ar:'مختبر'          }, category:{ en:'Science',     ar:'علوم'       } },
      { word:{ en:'Hotel',        ar:'فندق'            }, category:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Police Station',ar:'مركز شرطة'    }, category:{ en:'Justice',     ar:'قانون'      } },
      { word:{ en:'Gym',          ar:'صالة رياضية'     }, category:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Cinema',       ar:'سينما'          }, category:{ en:'Arts',        ar:'فنون'       } },
      { word:{ en:'Zoo',          ar:'حديقة حيوان'    }, category:{ en:'Nature',      ar:'طبيعة'      } },
      { word:{ en:'Submarine',    ar:'غواصة'          }, category:{ en:'Military',    ar:'عسكري'      } },
      { word:{ en:'Cruise Ship',  ar:'سفينة سياحية'  }, category:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Supermarket',  ar:'سوبرماركت'       }, category:{ en:'Commerce',    ar:'تجارة'      } },
    ],
  },
  {
    name: 'Vehicles',
    words: [
      { word:{ en:'Helicopter',  ar:'مروحية'          }, category:{ en:'Aviation',    ar:'طيران'      } },
      { word:{ en:'Ambulance',   ar:'إسعاف'           }, category:{ en:'Health',      ar:'صحة'       } },
      { word:{ en:'Tanker',      ar:'ناقلة نفط'       }, category:{ en:'Industry',    ar:'صناعة'      } },
      { word:{ en:'Race Car',    ar:'سيارة سباق'     }, category:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Train',       ar:'قطار'             }, category:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Sailboat',    ar:'قارب شراعي'     }, category:{ en:'Travel',      ar:'سفر'       } },
    ],
  },
  {
    name: 'Professions',
    words: [
      { word:{ en:'Surgeon',    ar:'جراح'           }, category:{ en:'Health',      ar:'صحة'      } },
      { word:{ en:'Judge',      ar:'قاضي'           }, category:{ en:'Justice',     ar:'قانون'     } },
      { word:{ en:'Astronaut',  ar:'رائد فضاء'      }, category:{ en:'Science',     ar:'علوم'      } },
      { word:{ en:'Chef',       ar:'طاهٍ'          }, category:{ en:'Food',        ar:'طعام'      } },
      { word:{ en:'Detective',  ar:'محقق'          }, category:{ en:'Justice',     ar:'قانون'     } },
      { word:{ en:'Pilot',      ar:'طيار'          }, category:{ en:'Aviation',    ar:'طيران'     } },
      { word:{ en:'Teacher',    ar:'معلم'          }, category:{ en:'Education',   ar:'تعليم'     } },
      { word:{ en:'Firefighter',ar:'رجل إطفاء'     }, category:{ en:'Safety',      ar:'أمن'       } },
    ],
  },
  {
    name: 'Events',
    words: [
      { word:{ en:'Wedding',    ar:'عرس'           }, category:{ en:'Social',      ar:'اجتماعي'    } },
      { word:{ en:'Election',   ar:'انتخابات'        }, category:{ en:'Politics',    ar:'سياسة'     } },
      { word:{ en:'Olympics',   ar:'أولمبياد'         }, category:{ en:'Sports',      ar:'رياضة'     } },
      { word:{ en:'Concert',    ar:'حفل موسيقي'     }, category:{ en:'Arts',        ar:'فنون'      } },
      { word:{ en:'Graduation', ar:'تخرج'          }, category:{ en:'Education',   ar:'تعليم'     } },
      { word:{ en:'Auction',    ar:'مزاد'          }, category:{ en:'Commerce',    ar:'تجارة'     } },
    ],
  },
];
