// wordPack.js — v10-fixed-b2
// Categories are now SHORT 1-2 word labels, not descriptive sentences.
export const WORD_PACKS = [
  {
    name: 'Places',
    words: [
      { word:{ en:'Airport',      ar:'مطار'           }, hint:{ en:'Travel',     ar:'سفر'      } },
      { word:{ en:'Hospital',     ar:'مستشفى'         }, hint:{ en:'Health',      ar:'صحة'       } },
      { word:{ en:'Bank',         ar:'بنك'              }, hint:{ en:'Finance',     ar:'مال'       } },
      { word:{ en:'Casino',       ar:'كازينو'          }, hint:{ en:'Games',       ar:'ترفيه'      } },
      { word:{ en:'University',   ar:'جامعة'           }, hint:{ en:'Education',   ar:'تعليم'      } },
      { word:{ en:'Stadium',      ar:'ملعب'            }, hint:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Mosque',       ar:'مسجد'            }, hint:{ en:'Religion',    ar:'دين'        } },
      { word:{ en:'Prison',       ar:'سجن'              }, hint:{ en:'Justice',     ar:'قانون'      } },
      { word:{ en:'Museum',       ar:'متحف'            }, hint:{ en:'Culture',     ar:'ثقافة'      } },
      { word:{ en:'Market',       ar:'سوق'              }, hint:{ en:'Commerce',    ar:'تجارة'      } },
      { word:{ en:'Farm',         ar:'مزرعة'           }, hint:{ en:'Nature',      ar:'طبيعة'      } },
      { word:{ en:'Space Station',ar:'محطة فضائية'    }, hint:{ en:'Science',     ar:'علوم'       } },
      { word:{ en:'Restaurant',   ar:'مطعم'           }, hint:{ en:'Food',        ar:'طعام'       } },
      { word:{ en:'Library',      ar:'مكتبة'           }, hint:{ en:'Education',   ar:'تعليم'      } },
      { word:{ en:'Embassy',      ar:'سفارة'           }, hint:{ en:'Politics',    ar:'سياسة'      } },
      { word:{ en:'Theater',      ar:'مسرح'            }, hint:{ en:'Arts',        ar:'فنون'       } },
      { word:{ en:'Laboratory',   ar:'مختبر'          }, hint:{ en:'Science',     ar:'علوم'       } },
      { word:{ en:'Hotel',        ar:'فندق'            }, hint:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Police Station',ar:'مركز شرطة'    }, hint:{ en:'Justice',     ar:'قانون'      } },
      { word:{ en:'Gym',          ar:'صالة رياضية'     }, hint:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Cinema',       ar:'سينما'          }, hint:{ en:'Arts',        ar:'فنون'       } },
      { word:{ en:'Zoo',          ar:'حديقة حيوان'    }, hint:{ en:'Nature',      ar:'طبيعة'      } },
      { word:{ en:'Submarine',    ar:'غواصة'          }, hint:{ en:'Military',    ar:'عسكري'      } },
      { word:{ en:'Cruise Ship',  ar:'سفينة سياحية'  }, hint:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Supermarket',  ar:'سوبرماركت'       }, hint:{ en:'Commerce',    ar:'تجارة'      } },
    ],
  },
  {
    name: 'Vehicles',
    words: [
      { word:{ en:'Helicopter',  ar:'مروحية'          }, hint:{ en:'Aviation',    ar:'طيران'      } },
      { word:{ en:'Ambulance',   ar:'إسعاف'           }, hint:{ en:'Health',      ar:'صحة'       } },
      { word:{ en:'Tanker',      ar:'ناقلة نفط'       }, hint:{ en:'Industry',    ar:'صناعة'      } },
      { word:{ en:'Race Car',    ar:'سيارة سباق'     }, hint:{ en:'Sports',      ar:'رياضة'      } },
      { word:{ en:'Train',       ar:'قطار'             }, hint:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Sailboat',    ar:'قارب شراعي'     }, hint:{ en:'Travel',      ar:'سفر'       } },
      { word:{ en:'Motorcycle',  ar:'دراجة نارية'     }, hint:{ en:'Road',        ar:'طريق'       } },
      { word:{ en:'Bicycle',     ar:'دراجة'           }, hint:{ en:'Pedal',       ar:'دواسة'      } },
      { word:{ en:'Scooter',     ar:'سكوتر'           }, hint:{ en:'Urban',       ar:'حضري'       } },
      { word:{ en:'Bus',         ar:'حافلة'           }, hint:{ en:'Public',      ar:'عام'        } },
      { word:{ en:'Truck',       ar:'شاحنة'           }, hint:{ en:'Cargo',       ar:'شحنة'       } },
      { word:{ en:'Tractor',     ar:'جرار'            }, hint:{ en:'Farm',        ar:'مزرعة'      } },
      { word:{ en:'Rocket',      ar:'صاروخ'           }, hint:{ en:'Space',       ar:'فضاء'       } },
      { word:{ en:'Canoe',       ar:'قارب'            }, hint:{ en:'River',       ar:'نهر'        } },
      { word:{ en:'Ferry',       ar:'عبارة'           }, hint:{ en:'Water',       ar:'ماء'        } },
      { word:{ en:'Tram',        ar:'ترام'            }, hint:{ en:'City',        ar:'مدينة'      } },
    ],
  },
  {
    name: 'Professions',
    words: [
      { word:{ en:'Surgeon',    ar:'جراح'           }, hint:{ en:'Health',      ar:'صحة'      } },
      { word:{ en:'Judge',      ar:'قاضي'           }, hint:{ en:'Justice',     ar:'قانون'     } },
      { word:{ en:'Astronaut',  ar:'رائد فضاء'      }, hint:{ en:'Science',     ar:'علوم'      } },
      { word:{ en:'Chef',       ar:'طاهٍ'          }, hint:{ en:'Food',        ar:'طعام'      } },
      { word:{ en:'Detective',  ar:'محقق'          }, hint:{ en:'Justice',     ar:'قانون'     } },
      { word:{ en:'Pilot',      ar:'طيار'          }, hint:{ en:'Aviation',    ar:'طيران'     } },
      { word:{ en:'Teacher',    ar:'معلم'          }, hint:{ en:'Education',   ar:'تعليم'     } },
      { word:{ en:'Firefighter',ar:'رجل إطفاء'     }, hint:{ en:'Safety',      ar:'أمن'       } },
      { word:{ en:'Engineer',   ar:'مهندس'          }, hint:{ en:'Build',       ar:'بناء'      } },
      { word:{ en:'Artist',     ar:'فنان'           }, hint:{ en:'Creative',    ar:'إبداع'     } },
      { word:{ en:'Writer',     ar:'كاتب'           }, hint:{ en:'Books',       ar:'كتب'       } },
      { word:{ en:'Nurse',      ar:'ممرض'           }, hint:{ en:'Care',        ar:'رعاية'     } },
      { word:{ en:'Lawyer',     ar:'محامٍ'           }, hint:{ en:'Court',       ar:'محكمة'     } },
      { word:{ en:'Architect',  ar:'مهندس معماري'    }, hint:{ en:'Design',      ar:'تصميم'     } },
      { word:{ en:'Plumber',    ar:'سباك'           }, hint:{ en:'Water',       ar:'ماء'       } },
      { word:{ en:'Electrician',ar:'كهربائي'        }, hint:{ en:'Power',       ar:'طاقة'      } },
      { word:{ en:'Journalist', ar:'صحفي'           }, hint:{ en:'News',        ar:'أخبار'     } },
      { word:{ en:'Dentist',    ar:'طبيب أسنان'     }, hint:{ en:'Teeth',       ar:'أسنان'     } },
      { word:{ en:'Baker',      ar:'خباز'           }, hint:{ en:'Bread',       ar:'خبز'       } },
      { word:{ en:'Farmer',     ar:'فلاح'           }, hint:{ en:'Crops',       ar:'محاصيل'    } },
    ],
  },
  {
    name: 'Events',
    words: [
      { word:{ en:'Wedding',    ar:'عرس'           }, hint:{ en:'Social',      ar:'اجتماعي'    } },
      { word:{ en:'Election',   ar:'انتخابات'        }, hint:{ en:'Politics',    ar:'سياسة'     } },
      { word:{ en:'Olympics',   ar:'أولمبياد'         }, hint:{ en:'Sports',      ar:'رياضة'     } },
      { word:{ en:'Concert',    ar:'حفل موسيقي'     }, hint:{ en:'Arts',        ar:'فنون'      } },
      { word:{ en:'Graduation', ar:'تخرج'          }, hint:{ en:'Education',   ar:'تعليم'     } },
      { word:{ en:'Auction',    ar:'مزاد'          }, hint:{ en:'Commerce',    ar:'تجارة'     } },
      { word:{ en:'Birthday',   ar:'عيد ميلاد'      }, hint:{ en:'Gift',        ar:'هدية'      } },
      { word:{ en:'Festival',   ar:'مهرجان'         }, hint:{ en:'Crowd',       ar:'حشد'       } },
      { word:{ en:'Carnival',   ar:'كرنفال'         }, hint:{ en:'Joy',         ar:'فرح'       } },
      { word:{ en:'Funeral',    ar:'جنازة'          }, hint:{ en:'Sad',         ar:'حزين'      } },
      { word:{ en:'Conference', ar:'مؤتمر'          }, hint:{ en:'Talk',        ar:'حديث'      } },
      { word:{ en:'Workshop',   ar:'ورشة عمل'       }, hint:{ en:'Skills',      ar:'مهارات'     } },
      { word:{ en:'Exhibition', ar:'معرض'           }, hint:{ en:'Display',     ar:'عرض'       } },
      { word:{ en:'Marathon',   ar:'ماراثون'        }, hint:{ en:'Race',        ar:'سباق'      } },
      { word:{ en:'Parade',     ar:'موكب'           }, hint:{ en:'Street',      ar:'شارع'      } },
      { word:{ en:'Eclipse',    ar:'كسوف'           }, hint:{ en:'Shadow',      ar:'ظل'        } },
    ],
  },
  {
    name: 'Nature',
    words: [
      { word:{ en:'Lion',       ar:'أسد'            }, hint:{ en:'King',        ar:'ملك'       } },
      { word:{ en:'Tiger',      ar:'نمر'            }, hint:{ en:'Stripes',     ar:'خطوط'      } },
      { word:{ en:'Elephant',   ar:'فيل'            }, hint:{ en:'Large',       ar:'ضخم'       } },
      { word:{ en:'Giraffe',    ar:'زرافة'          }, hint:{ en:'Neck',        ar:'رقبة'      } },
      { word:{ en:'Dolphin',    ar:'دلفين'          }, hint:{ en:'Smart',       ar:'ذكي'       } },
      { word:{ en:'Shark',      ar:'قرش'            }, hint:{ en:'Teeth',       ar:'أسنان'     } },
      { word:{ en:'Eagle',      ar:'نسر'            }, hint:{ en:'Sky',         ar:'سماء'      } },
      { word:{ en:'Owl',        ar:'بومة'           }, hint:{ en:'Night',       ar:'ليل'       } },
      { word:{ en:'Mountain',   ar:'جبل'            }, hint:{ en:'High',        ar:'مرتفع'     } },
      { word:{ en:'River',      ar:'نهر'            }, hint:{ en:'Flow',        ar:'جريان'     } },
      { word:{ en:'Ocean',      ar:'محيط'           }, hint:{ en:'Deep',        ar:'عميق'      } },
      { word:{ en:'Forest',     ar:'غابة'           }, hint:{ en:'Trees',       ar:'أشجار'     } },
      { word:{ en:'Desert',     ar:'صحراء'          }, hint:{ en:'Sand',        ar:'رمل'       } },
      { word:{ en:'Cactus',     ar:'صبار'           }, hint:{ en:'Dry',         ar:'جاف'       } },
      { word:{ en:'Rose',       ar:'وردة'           }, hint:{ en:'Scent',       ar:'عطر'       } },
      { word:{ en:'Oak',        ar:'بلوط'           }, hint:{ en:'Wood',        ar:'خشب'       } },
      { word:{ en:'Volcano',    ar:'بركان'          }, hint:{ en:'Lava',        ar:'حمم'       } },
      { word:{ en:'Waterfall',  ar:'شلال'           }, hint:{ en:'Height',      ar:'ارتفاع'     } },
      { word:{ en:'Thunder',    ar:'رعد'            }, hint:{ en:'Sound',       ar:'صوت'       } },
      { word:{ en:'Rainbow',    ar:'قوس قزح'        }, hint:{ en:'Colors',      ar:'ألوان'      } },
    ],
  },
  {
    name: 'Food',
    words: [
      { word:{ en:'Pizza',      ar:'بيتزا'          }, hint:{ en:'Round',       ar:'دائرية'     } },
      { word:{ en:'Burger',     ar:'برجر'           }, hint:{ en:'Meat',        ar:'لحم'       } },
      { word:{ en:'Sushi',      ar:'سوشي'           }, hint:{ en:'Fish',        ar:'سمك'       } },
      { word:{ en:'Coffee',     ar:'قهوة'           }, hint:{ en:'Caffeine',    ar:'كافيين'     } },
      { word:{ en:'Tea',        ar:'شاي'            }, hint:{ en:'Leaves',      ar:'أوراق'      } },
      { word:{ en:'Chocolate',  ar:'شوكولاتة'       }, hint:{ en:'Dark',        ar:'داكنة'      } },
      { word:{ en:'Ice Cream',  ar:'مثلجات'         }, hint:{ en:'Cold',        ar:'بارد'       } },
      { word:{ en:'Apple',      ar:'تفاح'           }, hint:{ en:'Red',         ar:'أحمر'       } },
      { word:{ en:'Banana',     ar:'موز'            }, hint:{ en:'Yellow',      ar:'أصفر'       } },
      { word:{ en:'Strawberry', ar:'فراولة'         }, hint:{ en:'Berry',       ar:'توت'       } },
      { word:{ en:'Orange',     ar:'برتقال'         }, hint:{ en:'Citrus',      ar:'حمضيات'     } },
      { word:{ en:'Bread',      ar:'خبز'            }, hint:{ en:'Dough',       ar:'عجين'      } },
      { word:{ en:'Cheese',     ar:'جبن'            }, hint:{ en:'Milk',        ar:'حليب'       } },
      { word:{ en:'Milk',       ar:'حليب'           }, hint:{ en:'White',       ar:'أبيض'       } },
      { word:{ en:'Water',      ar:'ماء'            }, hint:{ en:'Clear',       ar:'صافٍ'       } },
      { word:{ en:'Salad',      ar:'سلطة'           }, hint:{ en:'Green',       ar:'أخضر'       } },
      { word:{ en:'Pasta',      ar:'معكرونة'        }, hint:{ en:'Wheat',       ar:'قمح'       } },
      { word:{ en:'Sandwich',   ar:'سندويش'         }, hint:{ en:'Bread',       ar:'خبز'       } },
      { word:{ en:'Honey',      ar:'عسل'            }, hint:{ en:'Bee',         ar:'نحلة'       } },
      { word:{ en:'Cake',       ar:'كعكة'           }, hint:{ en:'Sweet',       ar:'حلو'       } },
    ],
  },
  {
    name: 'Technology',
    words: [
      { word:{ en:'Computer',   ar:'حاسوب'          }, hint:{ en:'Data',        ar:'بيانات'     } },
      { word:{ en:'Smartphone', ar:'هاتف ذكي'       }, hint:{ en:'Mobile',      ar:'متنقل'      } },
      { word:{ en:'Internet',   ar:'إنترنت'         }, hint:{ en:'Web',         ar:'شبكة'       } },
      { word:{ en:'Robot',      ar:'روبوت'          }, hint:{ en:'AI',          ar:'ذكاء'       } },
      { word:{ en:'Drone',      ar:'درون'           }, hint:{ en:'Flight',      ar:'طيران'      } },
      { word:{ en:'Camera',     ar:'كاميرا'         }, hint:{ en:'Lens',        ar:'عدسة'       } },
      { word:{ en:'Headphones', ar:'سماعات'         }, hint:{ en:'Sound',       ar:'صوت'       } },
      { word:{ en:'Television', ar:'تلفاز'          }, hint:{ en:'Screen',      ar:'شاشة'       } },
      { word:{ en:'Satellite',  ar:'قمر صناعي'      }, hint:{ en:'Orbit',       ar:'مدار'       } },
      { word:{ en:'Printer',    ar:'طابعة'          }, hint:{ en:'Ink',         ar:'حبر'        } },
      { word:{ en:'Battery',    ar:'بطارية'         }, hint:{ en:'Energy',      ar:'طاقة'       } },
      { word:{ en:'Keyboard',   ar:'لوحة مفاتيح'    }, hint:{ en:'Keys',        ar:'مفاتيح'     } },
      { word:{ en:'Mouse',      ar:'فأر'            }, hint:{ en:'Click',       ar:'نقرة'       } },
      { word:{ en:'Wi-Fi',      ar:'واي فاي'        }, hint:{ en:'Signal',      ar:'إشارة'      } },
      { word:{ en:'Software',   ar:'برمجيات'        }, hint:{ en:'Code',        ar:'برمجة'      } },
    ],
  },
  {
    name: 'Everyday',
    words: [
      { word:{ en:'Pencil',     ar:'قلم رصاص'       }, hint:{ en:'Write',       ar:'كتابة'      } },
      { word:{ en:'Pen',        ar:'قلم'            }, hint:{ en:'Ink',         ar:'حبر'        } },
      { word:{ en:'Notebook',   ar:'دفتر'           }, hint:{ en:'Notes',       ar:'ملاحظات'    } },
      { word:{ en:'Key',        ar:'مفتاح'          }, hint:{ en:'Lock',        ar:'قفل'        } },
      { word:{ en:'Wallet',     ar:'محفظة'          }, hint:{ en:'Cash',        ar:'نقد'        } },
      { word:{ en:'Umbrella',   ar:'مظلة'           }, hint:{ en:'Rain',        ar:'مطر'        } },
      { word:{ en:'Clock',      ar:'ساعة'           }, hint:{ en:'Time',        ar:'وقت'        } },
      { word:{ en:'Mirror',     ar:'مرآة'           }, hint:{ en:'Reflect',     ar:'انعكاس'     } },
      { word:{ en:'Glass',      ar:'كأس'            }, hint:{ en:'Drink',       ar:'شرب'        } },
      { word:{ en:'Plate',      ar:'صحن'            }, hint:{ en:'Eat',         ar:'أكل'        } },
      { word:{ en:'Fork',       ar:'شوكة'           }, hint:{ en:'Tool',        ar:'أداة'       } },
      { word:{ en:'Spoon',      ar:'ملعقة'          }, hint:{ en:'Tool',        ar:'أداة'       } },
      { word:{ en:'Knife',      ar:'سكين'           }, hint:{ en:'Sharp',       ar:'حاد'        } },
      { word:{ en:'Chair',      ar:'كرسي'           }, hint:{ en:'Sit',         ar:'جلوس'       } },
      { word:{ en:'Table',      ar:'طاولة'          }, hint:{ en:'Flat',        ar:'مسطح'       } },
      { word:{ en:'Bed',        ar:'سرير'           }, hint:{ en:'Sleep',       ar:'نوم'        } },
      { word:{ en:'Window',     ar:'نافذة'          }, hint:{ en:'Glass',       ar:'زجاج'       } },
      { word:{ en:'Door',       ar:'باب'            }, hint:{ en:'Entry',       ar:'مدخل'       } },
      { word:{ en:'Backpack',   ar:'حقيبة ظهر'      }, hint:{ en:'Bag',         ar:'حقيبة'      } },
      { word:{ en:'Soap',       ar:'صابون'          }, hint:{ en:'Clean',       ar:'نظيف'       } },
    ],
  },
  {
    name: 'Science',
    words: [
      { word:{ en:'Atom',       ar:'ذرة'            }, hint:{ en:'Small',       ar:'صغير'       } },
      { word:{ en:'DNA',        ar:'حمض نووي'       }, hint:{ en:'Life',        ar:'حياة'       } },
      { word:{ en:'Gravity',    ar:'جاذبية'         }, hint:{ en:'Force',       ar:'قوة'        } },
      { word:{ en:'Oxygen',     ar:'أكسجين'         }, hint:{ en:'Gas',         ar:'غاز'        } },
      { word:{ en:'Pyramid',    ar:'هرم'            }, hint:{ en:'Stone',       ar:'حجر'        } },
      { word:{ en:'Castle',     ar:'قلعة'           }, hint:{ en:'Wall',        ar:'جدار'       } },
      { word:{ en:'Knight',     ar:'فارس'           }, hint:{ en:'Armor',       ar:'درع'        } },
      { word:{ en:'Viking',     ar:'فايكنج'         }, hint:{ en:'Ship',        ar:'سفينة'      } },
      { word:{ en:'Fossil',     ar:'أحفورة'         }, hint:{ en:'Old',         ar:'قديم'       } },
      { word:{ en:'Microscope', ar:'مجهر'           }, hint:{ en:'Zoom',        ar:'تكبير'      } },
      { word:{ en:'Telescope',  ar:'تلسكوب'         }, hint:{ en:'Far',         ar:'بعيد'       } },
      { word:{ en:'Evolution',  ar:'تطور'           }, hint:{ en:'Change',      ar:'تغيير'      } },
      { word:{ en:'Electricity',ar:'كهرباء'         }, hint:{ en:'Shock',       ar:'صدمة'       } },
      { word:{ en:'Compass',    ar:'بوصلة'          }, hint:{ en:'North',       ar:'شمال'       } },
      { word:{ en:'Map',        ar:'خريطة'          }, hint:{ en:'Paper',       ar:'ورق'        } },
    ],
  },
  {
    name: 'Mythology',
    words: [
      { word:{ en:'Dragon',     ar:'تنين'           }, hint:{ en:'Fire',        ar:'نار'        } },
      { word:{ en:'Phoenix',    ar:'عنقاء'          }, hint:{ en:'Ash',         ar:'رماد'       } },
      { word:{ en:'Unicorn',    ar:'وحيد القرن'      }, hint:{ en:'Horn',        ar:'قرن'        } },
      { word:{ en:'Mermaid',    ar:'حورية البحر'     }, hint:{ en:'Tail',        ar:'ذيل'        } },
      { word:{ en:'Giant',      ar:'عملاق'          }, hint:{ en:'Tall',        ar:'طويل'       } },
      { word:{ en:'Ghost',      ar:'شبح'            }, hint:{ en:'Spirit',      ar:'روح'        } },
      { word:{ en:'Vampire',    ar:'مصاص دماء'      }, hint:{ en:'Blood',       ar:'دم'         } },
      { word:{ en:'Werewolf',   ar:'مستذئب'         }, hint:{ en:'Moon',        ar:'قمر'        } },
      { word:{ en:'Wizard',     ar:'ساحر'           }, hint:{ en:'Magic',       ar:'سحر'        } },
      { word:{ en:'Fairy',      ar:'جنية'           }, hint:{ en:'Wings',       ar:'أجنحة'      } },
    ],
  },
  {
    name: 'Sports',
    words: [
      { word:{ en:'Football',   ar:'كرة القدم'      }, hint:{ en:'Goal',        ar:'هدف'        } },
      { word:{ en:'Basketball', ar:'كرة السلة'      }, hint:{ en:'Hoop',        ar:'سلة'        } },
      { word:{ en:'Tennis',     ar:'كرة المضرب'     }, hint:{ en:'Racket',      ar:'مضرب'       } },
      { word:{ en:'Swimming',   ar:'سباحة'          }, hint:{ en:'Water',       ar:'ماء'        } },
      { word:{ en:'Running',    ar:'جري'            }, hint:{ en:'Fast',        ar:'سريع'       } },
      { word:{ en:'Cycling',    ar:'ركوب الدراجات'   }, hint:{ en:'Bike',        ar:'دراجة'      } },
      { word:{ en:'Boxing',     ar:'ملاكمة'         }, hint:{ en:'Gloves',      ar:'قفازات'     } },
      { word:{ en:'Karate',     ar:'كاراتيه'        }, hint:{ en:'Belt',        ar:'حزام'       } },
      { word:{ en:'Golf',       ar:'جولف'           }, hint:{ en:'Hole',        ar:'حفرة'       } },
      { word:{ en:'Skiing',     ar:'تزلج'           }, hint:{ en:'Snow',        ar:'ثلج'        } },
    ],
  },
];

export function getRandomWord() {
  const flat = WORD_PACKS.flatMap(pack => pack.words);
  return flat[Math.floor(Math.random() * flat.length)];
}
